name: Giyin
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #firebase
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.1
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4

  #weather packages
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.4.0
  location: ^4.4.0
  http: ^0.13.6
  geolocator: ^9.0.2
  #state management
  provider: ^6.0.5
  riverpod: ^2.3.6
  #translate
  flutter_translate: ^4.0.4
  intl: ^0.18.1
  #calendar
  table_calendar: ^3.0.9
  #wardrobe
  image_picker: ^0.8.9
  image_cropper: ^4.0.0
  multi_select_flutter: ^4.1.3
  dropdown_button2: ^2.3.4
  flutter_snake_navigationbar: ^0.6.1
  smooth_page_indicator: ^1.1.0
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Italic.ttf
