name: f6_bootcamp
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #firebase
  firebase_core: ^2.13.1

  #weather packages
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.4.0
  location: ^4.4.0
  http: ^1.0.0
  geolocator: ^9.0.2

  #state management
  provider: ^6.0.5
  riverpod: ^2.3.6

  #translate
  flutter_translate: ^4.0.4
  intl: ^0.18.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Italic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
